/*
 * Adversarial session regression suite. See test_regression_password.c
 * for the same philosophy applied here: this isn't the happy path
 * (test_session.c covers that) - it's the shapes of input and usage
 * pattern a real attacker, a stale client, or a buggy caller would
 * actually produce.
 */

#include "blue-bird/security/session.h"

#include "session_store.h"

#include <blue-bird/error/assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void test_adversarial_expired_session(void)
{
    printf("\texpired session is rejected, not just \"old\"...\n");
    fflush(stdout);

    bb_session_t session;
    bb_session_create("regression-user-1", -1, &session);

    bb_session_t fetched;
    bb_error_t err = bb_session_get(session.id, &fetched);

    BB_ASSERT(err.code == BB_ERR_SESSION_EXPIRED);

    /* An expired-but-not-yet-cleaned-up session must not be usable
     * twice differently - looking it up again gives the same answer. */
    err = bb_session_get(session.id, &fetched);
    BB_ASSERT(err.code == BB_ERR_SESSION_EXPIRED);
}

void test_adversarial_unknown_session(void)
{
    printf("\tunknown session ID (well-formed, never issued)...\n");
    fflush(stdout);

    bb_session_t fetched;

    /* Correct shape (64 hex-looking chars) but never actually
     * generated by bb_session_create(). */
    bb_error_t err = bb_session_get(
        "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
        &fetched);

    BB_ASSERT(err.code == BB_ERR_SESSION_NOT_FOUND);
}

void test_adversarial_deleted_session(void)
{
    printf("\tdeleted session cannot be reused...\n");
    fflush(stdout);

    bb_session_t session;
    bb_session_create("regression-user-2", 3600, &session);

    BB_ASSERT(bb_session_destroy(session.id).code == BB_OK);

    bb_session_t fetched;
    BB_ASSERT(bb_session_get(session.id, &fetched).code == BB_ERR_SESSION_NOT_FOUND);

    /* Destroying it a second time must fail cleanly, not crash or
     * "succeed" on a session that's already gone. */
    BB_ASSERT(bb_session_destroy(session.id).code == BB_ERR_SESSION_NOT_FOUND);
}

void test_adversarial_malformed_ids(void)
{
    printf("\tmalformed session IDs (wrong shapes)...\n");
    fflush(stdout);

    bb_session_t fetched;

    /* Empty. */
    BB_ASSERT(bb_session_get("", &fetched).code != BB_OK);

    /* Single character. */
    BB_ASSERT(bb_session_get("a", &fetched).code != BB_OK);

    /* Right length, non-hex characters. */
    char non_hex[BB_SESSION_ID_SIZE];
    memset(non_hex, 'z', sizeof(non_hex) - 1);
    non_hex[sizeof(non_hex) - 1] = '\0';
    BB_ASSERT(bb_session_get(non_hex, &fetched).code != BB_OK);

    /* Way longer than any real session ID - must not overread or
     * crash just because the string keeps going. */
    size_t huge_len = 1024 * 1024;
    char *huge_id = malloc(huge_len + 1);
    BB_ASSERT(huge_id != NULL);
    memset(huge_id, '1', huge_len);
    huge_id[huge_len] = '\0';
    BB_ASSERT(bb_session_get(huge_id, &fetched).code != BB_OK);
    BB_ASSERT(bb_session_destroy(huge_id).code != BB_OK);
    free(huge_id);
}

void test_adversarial_repeated_creation(void)
{
    printf("\trepeated session creation for the same user...\n");
    fflush(stdout);

    enum { N = 500 };
    bb_session_t sessions[N];

    for (int i = 0; i < N; i++)
    {
        bb_error_t err = bb_session_create("regression-repeat-user", 3600, &sessions[i]);
        BB_ASSERT(err.code == BB_OK);
    }

    /* Every ID must be unique - no collisions, no accidental reuse of
     * a stale buffer across calls. */
    for (int i = 0; i < N; i++)
    {
        for (int j = i + 1; j < N; j++)
        {
            BB_ASSERT(strcmp(sessions[i].id, sessions[j].id) != 0);
        }
    }

    /* And every single one must still be independently retrievable and
     * carry the right user_id - creating #500 must not have corrupted
     * or evicted #1. */
    for (int i = 0; i < N; i++)
    {
        bb_session_t fetched;
        bb_error_t err = bb_session_get(sessions[i].id, &fetched);

        BB_ASSERT(err.code == BB_OK);
        BB_ASSERT(strcmp(fetched.user_id, "regression-repeat-user") == 0);
    }

    /* Clean up after ourselves so later tests in this process (if any
     * share the store) aren't affected by 500 extra live sessions. */
    for (int i = 0; i < N; i++)
    {
        bb_session_destroy(sessions[i].id);
    }
}

void test_adversarial_cleanup_under_mixed_load(void)
{
    printf("\tcleanup with a mix of expired and live sessions...\n");
    fflush(stdout);

    enum { N = 100 };
    bb_session_t sessions[N];

    for (int i = 0; i < N; i++)
    {
        /* Alternate expired/live. */
        time_t ttl = (i % 2 == 0) ? -1 : 3600;
        bb_error_t err = bb_session_create("regression-mixed-user", ttl, &sessions[i]);
        BB_ASSERT(err.code == BB_OK);
    }

    size_t before = _bb_session_store_count();

    BB_ASSERT(bb_session_cleanup_expired().code == BB_OK);

    size_t after = _bb_session_store_count();

    BB_ASSERT(after <= before);

    for (int i = 0; i < N; i++)
    {
        bb_session_t fetched;
        bb_error_t err = bb_session_get(sessions[i].id, &fetched);

        if (i % 2 == 0)
        {
            BB_ASSERT(err.code == BB_ERR_SESSION_NOT_FOUND); /* swept away */
        }
        else
        {
            BB_ASSERT(err.code == BB_OK); /* survived */
            bb_session_destroy(sessions[i].id); /* tidy up */
        }
    }
}

int main(void)
{
    printf("Running adversarial session regression suite...\n");
    fflush(stdout);

    test_adversarial_expired_session();
    test_adversarial_unknown_session();
    test_adversarial_deleted_session();
    test_adversarial_malformed_ids();
    test_adversarial_repeated_creation();
    test_adversarial_cleanup_under_mixed_load();

    printf("All tests passed.\n");

    return 0;
}
