#ifndef BB_SECURITY_CONFIG_H
#define BB_SECURITY_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>
#include <time.h>

#include <blue-bird/error/error.h>
#include <blue-bird/security/session.h> /* BB_ERR_INVALID_SECURITY_CONFIG */
#include <blue-bird/utils/json.h>

/*
 * Explicit, validated security policy for the password/session
 * subsystem.
 *
 * Every field here used to be a hardcoded constant somewhere in
 * password.c/session.c/auth.c - see bb_security_config_default() for
 * exactly what each one used to be. The goal isn't to make Blue-Bird's
 * security posture configurable for its own sake; it's so a choice
 * that was baked into the source years ago is instead an explicit,
 * validated value an application can see, override deliberately, and
 * reason about.
 */
typedef struct
{
    /* PBKDF2-HMAC-SHA256 iterations used by bb_password_hash(). Higher
     * costs more CPU per hash - for a legitimate login and for an
     * attacker's guess alike. bb_password_verify() does not use this:
     * the iteration count is embedded in the stored record itself, so
     * verification always uses whatever count the password was
     * actually hashed with, even if this value changes later. */
    uint32_t password_pbkdf2_iterations;

    /* Passwords longer than this are rejected by bb_password_hash()
     * and bb_password_verify() with BB_ERR_PASSWORD_TOO_LONG rather
     * than being processed. This bounds the size of input pushed
     * through the password pipeline per attempt; it is not a claim
     * that long passwords are weak. */
    size_t password_max_length;

    /* Default lifetime, in seconds, of sessions created by
     * bb_auth_login(). bb_session_create() still takes its own `ttl`
     * argument for direct callers - this only supplies the default
     * used by the login convenience path. */
    time_t session_lifetime_seconds;

    /* Length, in hex characters, of session IDs generated by
     * bb_session_create(). Must fit within BB_SESSION_ID_SIZE - 1.
     * Defaults to the full buffer (maximum entropy); lowering this is
     * a deliberate, validated trade-off against BB_SESSION_ID_LENGTH_MIN
     * (128 bits), not something that can happen by accident. */
    size_t session_id_length;
} bb_security_config_t;

/* Well-known bb_config (blue-bird/utils/bb_config.h) keys, for use with
 * bb_security_config_from_json(). Each is optional - see that
 * function's documentation. */
#define BB_CONFIG_KEY_SECURITY_PASSWORD_ITERATIONS "security_password_iterations"
#define BB_CONFIG_KEY_SECURITY_PASSWORD_MAX_LENGTH "security_password_max_length"
#define BB_CONFIG_KEY_SECURITY_SESSION_LIFETIME_SECONDS "security_session_lifetime_seconds"
#define BB_CONFIG_KEY_SECURITY_SESSION_ID_LENGTH "security_session_id_length"

/*
 * Fills `out_config` with Blue-Bird's built-in secure defaults - the
 * same values that were previously hardcoded constants throughout this
 * module. Always succeeds; the result always passes
 * bb_security_config_validate().
 */
void bb_security_config_default(bb_security_config_t *out_config);

/*
 * Checks that every field of `config` is within a safe, supported
 * range. Does not touch the currently-active configuration - use this
 * to validate a config before deciding whether to install it, or just
 * to sanity-check one built by hand.
 *
 * Returns BB_ERR_NULL if `config` is NULL, or
 * BB_ERR_INVALID_SECURITY_CONFIG naming the first out-of-range field
 * found.
 */
bb_error_t bb_security_config_validate(const bb_security_config_t *config);

/*
 * Validates `config` and, if valid, installs it as the process-wide
 * active security configuration used by bb_password_hash(),
 * bb_password_verify(), bb_session_create(), and bb_auth_login().
 *
 * On validation failure, the currently-active configuration (or the
 * default, if this has never been called) is left untouched and the
 * same error bb_security_config_validate() would have returned is
 * returned here.
 *
 * Not thread-safe - call this once during application startup, before
 * spinning up whatever serves requests. This matches the rest of
 * Blue-Bird's security module, which assumes a single-threaded
 * event-loop runtime (see internal/session_store.h).
 */
bb_error_t bb_security_config_set(const bb_security_config_t *config);

/*
 * Returns the process-wide active security configuration, defaulting
 * to bb_security_config_default() if bb_security_config_set() has
 * never been called. Never returns NULL. The returned pointer is only
 * valid until the next call to bb_security_config_set().
 */
const bb_security_config_t *bb_security_config_get(void);

/*
 * Populates `out_config` from a config object, as loaded by
 * bb_config_load_env()/bb_config_load_json() (blue-bird/utils/bb_config.h).
 *
 * Starts from bb_security_config_default() and overrides only the
 * fields whose BB_CONFIG_KEY_SECURITY_* key is actually present in
 * `config` - every key is optional, so a config file only needs to
 * mention the settings it actually wants to change. The combined
 * result is validated before being returned; on failure `out_config`
 * is left holding the (valid) defaults and an error is returned.
 *
 * This does not call bb_security_config_set() - call that yourself
 * once you're happy with the result, the same way
 * bb_tls_config_from_json() (blue-bird/web/tls.h) doesn't start a
 * server on your behalf.
 *
 * Fails with BB_ERR_NULL if `config` or `out_config` is NULL, or
 * whatever bb_security_config_validate() returns if the combined
 * result is out of range.
 */
bb_error_t bb_security_config_from_json(bb_json_t *config, bb_security_config_t *out_config);


#ifdef __cplusplus
}
#endif

#endif
