#ifndef BB_SECURITY_SESSION_H
#define BB_SECURITY_SESSION_H

#ifdef __cplusplus
extern "C" {
#endif


#include <time.h>

#include "blue-bird/error/error.h"

/*
 * Session IDs are BB_SESSION_ID_SIZE - 1 hex characters (the array
 * includes the NUL terminator), generated by Phase 1's OS-backed
 * CSPRNG (see internal/random.h) - never rand()/srand(). At 63 hex
 * characters that's 252 bits of raw randomness (31.5 bytes), well
 * above the ~128-bit floor generally recommended for unguessable
 * session identifiers.
 */
#define BB_SESSION_ID_SIZE 64
#define BB_USER_ID_SIZE 64

#define BB_SESSION_DEFAULT_TTL 3600

typedef struct
{
    char id[BB_SESSION_ID_SIZE];
    char user_id[BB_USER_ID_SIZE];
    time_t expires_at;
} bb_session_t;

enum bb_security_error {
    BB_ERR_INVALID_CREDENTIALS = 1000,
    BB_ERR_SESSION_EXPIRED,
    BB_ERR_SESSION_NOT_FOUND,
    BB_ERR_HASH_FAILED,
    BB_ERR_RANDOM_FAILED,
    BB_ERR_PASSWORD_TOO_LONG,
    BB_ERR_INVALID_SECURITY_CONFIG
};

bb_error_t bb_session_create(const char *user_id, time_t ttl, bb_session_t *session);

bb_error_t bb_session_get(const char *session_id, bb_session_t *session);

bb_error_t bb_session_destroy(const char *session_id);

/*
 * Sweeps the session store and removes every session that has expired.
 * This does not run on a timer by itself - the security module has no
 * knowledge of Blue-Bird's runtime/event loop. Call this periodically
 * from wherever your application already drives one, for example with
 * Blue-Bird's own runtime timers:
 *
 *   void cleanup_task(bb_task_t *task, void *userdata)
 *   {
 *       (void)task;
 *       (void)userdata;
 *
 *       bb_session_cleanup_expired();
 *   }
 *
 *   bb_runtime_set_interval(runtime, 60000, cleanup_task, NULL);
 *
 * Until this (or your own equivalent) is called, expired sessions are
 * still correctly rejected by bb_session_get() - they just continue to
 * occupy memory in the store until swept.
 */
bb_error_t bb_session_cleanup_expired(void);


#ifdef __cplusplus
}
#endif

#endif
