#include "app_html.h"

const char *APP_INDEX_HTML =
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "<title>Blue-Bird Chat</title>\n"
    "<style>\n"
    "  :root {\n"
    "    --accent: #2AABEE;\n"
    "    --accent-dark: #229ED9;\n"
    "    --bg: #ffffff;\n"
    "    --sidebar-bg: #f7f8fa;\n"
    "    --border: #e4e6eb;\n"
    "    --text: #1c1e21;\n"
    "    --muted: #8a8d91;\n"
    "    --bubble-own: #e3f6d8;\n"
    "    --bubble-other: #ffffff;\n"
    "    --danger: #e35555;\n"
    "  }\n"
    "  * { box-sizing: border-box; }\n"
    "  html, body {\n"
    "    height: 100%;\n"
    "    margin: 0;\n"
    "    font-family: -apple-system, system-ui, Segoe UI, Roboto, Helvetica, Arial, sans-serif;\n"
    "    color: var(--text);\n"
    "    background: var(--sidebar-bg);\n"
    "  }\n"
    "  .hidden { display: none !important; }\n"
    "\n"
    "  /* ---------- Auth screen ---------- */\n"
    "  #auth-screen {\n"
    "    height: 100%;\n"
    "    display: flex;\n"
    "    align-items: center;\n"
    "    justify-content: center;\n"
    "  }\n"
    "  .auth-card {\n"
    "    width: 340px;\n"
    "    background: var(--bg);\n"
    "    border-radius: 12px;\n"
    "    box-shadow: 0 4px 24px rgba(0,0,0,0.08);\n"
    "    padding: 28px 28px 24px;\n"
    "  }\n"
    "  .auth-logo {\n"
    "    width: 56px;\n"
    "    height: 56px;\n"
    "    border-radius: 50%;\n"
    "    background: linear-gradient(135deg, var(--accent), var(--accent-dark));\n"
    "    display: flex;\n"
    "    align-items: center;\n"
    "    justify-content: center;\n"
    "    color: #fff;\n"
    "    font-size: 26px;\n"
    "    font-weight: 600;\n"
    "    margin: 0 auto 14px;\n"
    "  }\n"
    "  .auth-title {\n"
    "    text-align: center;\n"
    "    font-size: 19px;\n"
    "    font-weight: 600;\n"
    "    margin-bottom: 4px;\n"
    "  }\n"
    "  .auth-subtitle {\n"
    "    text-align: center;\n"
    "    color: var(--muted);\n"
    "    font-size: 13px;\n"
    "    margin-bottom: 20px;\n"
    "  }\n"
    "  .auth-tabs {\n"
    "    display: flex;\n"
    "    background: var(--sidebar-bg);\n"
    "    border-radius: 8px;\n"
    "    padding: 3px;\n"
    "    margin-bottom: 18px;\n"
    "  }\n"
    "  .auth-tab {\n"
    "    flex: 1;\n"
    "    text-align: center;\n"
    "    padding: 8px 0;\n"
    "    font-size: 13px;\n"
    "    font-weight: 600;\n"
    "    border-radius: 6px;\n"
    "    cursor: pointer;\n"
    "    color: var(--muted);\n"
    "    user-select: none;\n"
    "  }\n"
    "  .auth-tab.active {\n"
    "    background: var(--bg);\n"
    "    color: var(--text);\n"
    "    box-shadow: 0 1px 3px rgba(0,0,0,0.12);\n"
    "  }\n"
    "  .field {\n"
    "    margin-bottom: 12px;\n"
    "  }\n"
    "  .field input {\n"
    "    width: 100%;\n"
    "    padding: 11px 12px;\n"
    "    border: 1px solid var(--border);\n"
    "    border-radius: 8px;\n"
    "    font-size: 14px;\n"
    "    outline: none;\n"
    "    background: var(--bg);\n"
    "  }\n"
    "  .field input:focus {\n"
    "    border-color: var(--accent);\n"
    "  }\n"
    "  .btn-primary {\n"
    "    width: 100%;\n"
    "    padding: 11px 0;\n"
    "    border: none;\n"
    "    border-radius: 8px;\n"
    "    background: var(--accent);\n"
    "    color: #fff;\n"
    "    font-size: 14px;\n"
    "    font-weight: 600;\n"
    "    cursor: pointer;\n"
    "    margin-top: 4px;\n"
    "  }\n"
    "  .btn-primary:hover { background: var(--accent-dark); }\n"
    "  .btn-primary:disabled { opacity: 0.6; cursor: default; }\n"
    "  .auth-error {\n"
    "    color: var(--danger);\n"
    "    font-size: 12.5px;\n"
    "    margin-top: 10px;\n"
    "    text-align: center;\n"
    "    min-height: 16px;\n"
    "  }\n"
    "\n"
    "  /* ---------- App screen ---------- */\n"
    "  #app-screen {\n"
    "    height: 100%;\n"
    "    display: flex;\n"
    "  }\n"
    "  #sidebar {\n"
    "    width: 300px;\n"
    "    min-width: 300px;\n"
    "    background: var(--sidebar-bg);\n"
    "    border-right: 1px solid var(--border);\n"
    "    display: flex;\n"
    "    flex-direction: column;\n"
    "  }\n"
    "  #sidebar-header {\n"
    "    padding: 14px 16px;\n"
    "    display: flex;\n"
    "    align-items: center;\n"
    "    justify-content: space-between;\n"
    "    border-bottom: 1px solid var(--border);\n"
    "  }\n"
    "  #me {\n"
    "    display: flex;\n"
    "    align-items: center;\n"
    "    gap: 10px;\n"
    "    font-weight: 600;\n"
    "    font-size: 14px;\n"
    "    overflow: hidden;\n"
    "  }\n"
    "  #logout-btn {\n"
    "    border: none;\n"
    "    background: none;\n"
    "    color: var(--muted);\n"
    "    cursor: pointer;\n"
    "    font-size: 12.5px;\n"
    "    font-weight: 600;\n"
    "  }\n"
    "  #logout-btn:hover { color: var(--danger); }\n"
    "  #search-wrap { padding: 10px 12px; }\n"
    "  #search-input {\n"
    "    width: 100%;\n"
    "    padding: 9px 12px;\n"
    "    border: 1px solid var(--border);\n"
    "    border-radius: 18px;\n"
    "    background: var(--bg);\n"
    "    font-size: 13px;\n"
    "    outline: none;\n"
    "  }\n"
    "  #user-list {\n"
    "    flex: 1;\n"
    "    overflow-y: auto;\n"
    "  }\n"
    "  .contact {\n"
    "    display: flex;\n"
    "    align-items: center;\n"
    "    gap: 10px;\n"
    "    padding: 10px 16px;\n"
    "    cursor: pointer;\n"
    "    border-left: 3px solid transparent;\n"
    "  }\n"
    "  .contact:hover { background: #eef0f2; }\n"
    "  .contact.active {\n"
    "    background: #e8f4fd;\n"
    "    border-left-color: var(--accent);\n"
    "  }\n"
    "  .avatar {\n"
    "    width: 40px;\n"
    "    height: 40px;\n"
    "    min-width: 40px;\n"
    "    border-radius: 50%;\n"
    "    background: linear-gradient(135deg, var(--accent), var(--accent-dark));\n"
    "    color: #fff;\n"
    "    display: flex;\n"
    "    align-items: center;\n"
    "    justify-content: center;\n"
    "    font-weight: 600;\n"
    "    font-size: 15px;\n"
    "    position: relative;\n"
    "  }\n"
    "  .presence-dot {\n"
    "    width: 10px;\n"
    "    height: 10px;\n"
    "    border-radius: 50%;\n"
    "    background: #c6c9cc;\n"
    "    border: 2px solid var(--sidebar-bg);\n"
    "    position: absolute;\n"
    "    right: -2px;\n"
    "    bottom: -2px;\n"
    "  }\n"
    "  .presence-dot.online { background: #4bc158; }\n"
    "  .contact-name {\n"
    "    font-size: 14px;\n"
    "    font-weight: 600;\n"
    "    white-space: nowrap;\n"
    "    overflow: hidden;\n"
    "    text-overflow: ellipsis;\n"
    "  }\n"
    "  .contact-sub {\n"
    "    font-size: 12px;\n"
    "    color: var(--muted);\n"
    "  }\n"
    "  #empty-users {\n"
    "    padding: 20px 16px;\n"
    "    color: var(--muted);\n"
    "    font-size: 13px;\n"
    "    text-align: center;\n"
    "  }\n"
    "\n"
    "  #chat-panel {\n"
    "    flex: 1;\n"
    "    display: flex;\n"
    "    flex-direction: column;\n"
    "    background: var(--bg);\n"
    "    min-width: 0;\n"
    "  }\n"
    "  #chat-header {\n"
    "    padding: 14px 20px;\n"
    "    border-bottom: 1px solid var(--border);\n"
    "    display: flex;\n"
    "    align-items: center;\n"
    "    gap: 12px;\n"
    "  }\n"
    "  #chat-header .contact-name { font-size: 15px; }\n"
    "  #chat-header .contact-sub { margin-top: 1px; }\n"
    "  #messages {\n"
    "    flex: 1;\n"
    "    overflow-y: auto;\n"
    "    padding: 18px 22px;\n"
    "    display: flex;\n"
    "    flex-direction: column;\n"
    "    gap: 8px;\n"
    "  }\n"
    "  .bubble-row {\n"
    "    display: flex;\n"
    "  }\n"
    "  .bubble-row.own { justify-content: flex-end; }\n"
    "  .bubble {\n"
    "    max-width: 62%;\n"
    "    padding: 9px 13px;\n"
    "    border-radius: 14px;\n"
    "    font-size: 14px;\n"
    "    line-height: 1.4;\n"
    "    word-wrap: break-word;\n"
    "    box-shadow: 0 1px 1px rgba(0,0,0,0.04);\n"
    "  }\n"
    "  .bubble-row.own .bubble {\n"
    "    background: var(--bubble-own);\n"
    "    border-bottom-right-radius: 4px;\n"
    "  }\n"
    "  .bubble-row:not(.own) .bubble {\n"
    "    background: var(--bubble-other);\n"
    "    border: 1px solid var(--border);\n"
    "    border-bottom-left-radius: 4px;\n"
    "  }\n"
    "  .bubble-time {\n"
    "    display: block;\n"
    "    font-size: 10.5px;\n"
    "    color: var(--muted);\n"
    "    margin-top: 3px;\n"
    "    text-align: right;\n"
    "  }\n"
    "  #composer {\n"
    "    display: flex;\n"
    "    gap: 10px;\n"
    "    padding: 14px 20px;\n"
    "    border-top: 1px solid var(--border);\n"
    "  }\n"
    "  #msg-input {\n"
    "    flex: 1;\n"
    "    padding: 11px 14px;\n"
    "    border: 1px solid var(--border);\n"
    "    border-radius: 20px;\n"
    "    font-size: 14px;\n"
    "    outline: none;\n"
    "    resize: none;\n"
    "  }\n"
    "  #msg-input:focus { border-color: var(--accent); }\n"
    "  #send-btn {\n"
    "    width: 42px;\n"
    "    height: 42px;\n"
    "    border-radius: 50%;\n"
    "    border: none;\n"
    "    background: var(--accent);\n"
    "    color: #fff;\n"
    "    cursor: pointer;\n"
    "    font-size: 16px;\n"
    "    flex-shrink: 0;\n"
    "  }\n"
    "  #send-btn:hover { background: var(--accent-dark); }\n"
    "  #send-btn:disabled { opacity: 0.5; cursor: default; }\n"
    "  #no-chat {\n"
    "    flex: 1;\n"
    "    display: flex;\n"
    "    align-items: center;\n"
    "    justify-content: center;\n"
    "    color: var(--muted);\n"
    "    font-size: 14px;\n"
    "    text-align: center;\n"
    "    padding: 20px;\n"
    "  }\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "<div id=\"auth-screen\">\n"
    "  <div class=\"auth-card\">\n"
    "    <div class=\"auth-logo\">BB</div>\n"
    "    <div class=\"auth-title\">Blue-Bird Chat</div>\n"
    "    <div class=\"auth-subtitle\">Simple, live messaging</div>\n"
    "\n"
    "    <div class=\"auth-tabs\">\n"
    "      <div class=\"auth-tab active\" data-tab=\"login\">Log in</div>\n"
    "      <div class=\"auth-tab\" data-tab=\"register\">Sign up</div>\n"
    "    </div>\n"
    "\n"
    "    <form id=\"login-form\">\n"
    "      <div class=\"field\"><input type=\"text\" id=\"login-username\" placeholder=\"Username\" autocomplete=\"username\" required></div>\n"
    "      <div class=\"field\"><input type=\"password\" id=\"login-password\" placeholder=\"Password\" autocomplete=\"current-password\" required></div>\n"
    "      <button type=\"submit\" class=\"btn-primary\">Log in</button>\n"
    "    </form>\n"
    "\n"
    "    <form id=\"register-form\" class=\"hidden\">\n"
    "      <div class=\"field\"><input type=\"text\" id=\"register-username\" placeholder=\"Choose a username\" autocomplete=\"username\" required></div>\n"
    "      <div class=\"field\"><input type=\"password\" id=\"register-password\" placeholder=\"Choose a password\" autocomplete=\"new-password\" required></div>\n"
    "      <button type=\"submit\" class=\"btn-primary\">Create account</button>\n"
    "    </form>\n"
    "\n"
    "    <div class=\"auth-error\" id=\"auth-error\"></div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<div id=\"app-screen\" class=\"hidden\">\n"
    "  <div id=\"sidebar\">\n"
    "    <div id=\"sidebar-header\">\n"
    "      <div id=\"me\">\n"
    "        <div class=\"avatar\" id=\"me-avatar\">?</div>\n"
    "        <span id=\"me-name\"></span>\n"
    "      </div>\n"
    "      <button id=\"logout-btn\">Log out</button>\n"
    "    </div>\n"
    "    <div id=\"search-wrap\">\n"
    "      <input type=\"text\" id=\"search-input\" placeholder=\"Search people...\">\n"
    "    </div>\n"
    "    <div id=\"user-list\"></div>\n"
    "  </div>\n"
    "\n"
    "  <div id=\"chat-panel\">\n"
    "    <div id=\"no-chat\">Pick someone on the left to start chatting.</div>\n"
    "\n"
    "    <div id=\"chat-header\" class=\"hidden\">\n"
    "      <div class=\"avatar\" id=\"peer-avatar\">?</div>\n"
    "      <div>\n"
    "        <div class=\"contact-name\" id=\"peer-name\"></div>\n"
    "        <div class=\"contact-sub\" id=\"peer-status\">offline</div>\n"
    "      </div>\n"
    "    </div>\n"
    "    <div id=\"messages\" class=\"hidden\"></div>\n"
    "    <div id=\"composer\" class=\"hidden\">\n"
    "      <input type=\"text\" id=\"msg-input\" placeholder=\"Write a message...\" autocomplete=\"off\">\n"
    "      <button id=\"send-btn\">&#10148;</button>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<script>\n"
    "(function () {\n"
    "  \"use strict\";\n"
    "\n"
    "  var state = {\n"
    "    me: null,\n"
    "    peer: null,\n"
    "    users: [],\n"
    "    ws: null,\n"
    "    wsReady: false,\n"
    "    loggedIn: false,\n"
    "    pollTimer: null\n"
    "  };\n"
    "\n"
    "  // ---------- helpers ----------\n"
    "\n"
    "  function $(id) { return document.getElementById(id); }\n"
    "\n"
    "  function getCookie(name) {\n"
    "    var parts = document.cookie.split(\";\");\n"
    "    for (var i = 0; i < parts.length; i++) {\n"
    "      var p = parts[i].trim();\n"
    "      if (p.indexOf(name + \"=\") === 0) {\n"
    "        return p.substring(name.length + 1);\n"
    "      }\n"
    "    }\n"
    "    return null;\n"
    "  }\n"
    "\n"
    "  function initials(name) {\n"
    "    return name ? name.charAt(0).toUpperCase() : \"?\";\n"
    "  }\n"
    "\n"
    "  function formatTime(unixSeconds) {\n"
    "    var d = new Date(unixSeconds * 1000);\n"
    "    var h = d.getHours().toString().padStart(2, \"0\");\n"
    "    var m = d.getMinutes().toString().padStart(2, \"0\");\n"
    "    return h + \":\" + m;\n"
    "  }\n"
    "\n"
    "  function api(path, options) {\n"
    "    options = options || {};\n"
    "    options.headers = Object.assign({ \"Content-Type\": \"application/json\" }, options.headers || {});\n"
    "    return fetch(path, options).then(function (resp) {\n"
    "      return resp.json().then(function (data) {\n"
    "        return { status: resp.status, ok: resp.ok, data: data };\n"
    "      });\n"
    "    });\n"
    "  }\n"
    "\n"
    "  // ---------- auth screen ----------\n"
    "\n"
    "  var authTabs = document.querySelectorAll(\".auth-tab\");\n"
    "  authTabs.forEach(function (tab) {\n"
    "    tab.addEventListener(\"click\", function () {\n"
    "      authTabs.forEach(function (t) { t.classList.remove(\"active\"); });\n"
    "      tab.classList.add(\"active\");\n"
    "      $(\"auth-error\").textContent = \"\";\n"
    "      if (tab.dataset.tab === \"login\") {\n"
    "        $(\"login-form\").classList.remove(\"hidden\");\n"
    "        $(\"register-form\").classList.add(\"hidden\");\n"
    "      } else {\n"
    "        $(\"register-form\").classList.remove(\"hidden\");\n"
    "        $(\"login-form\").classList.add(\"hidden\");\n"
    "      }\n"
    "    });\n"
    "  });\n"
    "\n"
    "  $(\"login-form\").addEventListener(\"submit\", function (e) {\n"
    "    e.preventDefault();\n"
    "    $(\"auth-error\").textContent = \"\";\n"
    "    var username = $(\"login-username\").value.trim();\n"
    "    var password = $(\"login-password\").value;\n"
    "    api(\"/api/login\", { method: \"POST\", body: JSON.stringify({ username: username, password: password }) })\n"
    "      .then(function (res) {\n"
    "        if (!res.ok) {\n"
    "          $(\"auth-error\").textContent = (res.data && res.data.error) || \"Login failed\";\n"
    "          return;\n"
    "        }\n"
    "        onAuthenticated(res.data.username);\n"
    "      })\n"
    "      .catch(function () { $(\"auth-error\").textContent = \"Network error\"; });\n"
    "  });\n"
    "\n"
    "  $(\"register-form\").addEventListener(\"submit\", function (e) {\n"
    "    e.preventDefault();\n"
    "    $(\"auth-error\").textContent = \"\";\n"
    "    var username = $(\"register-username\").value.trim();\n"
    "    var password = $(\"register-password\").value;\n"
    "    api(\"/api/register\", { method: \"POST\", body: JSON.stringify({ username: username, password: password }) })\n"
    "      .then(function (res) {\n"
    "        if (!res.ok) {\n"
    "          $(\"auth-error\").textContent = (res.data && res.data.error) || \"Registration failed\";\n"
    "          return;\n"
    "        }\n"
    "        onAuthenticated(res.data.username);\n"
    "      })\n"
    "      .catch(function () { $(\"auth-error\").textContent = \"Network error\"; });\n"
    "  });\n"
    "\n"
    "  $(\"logout-btn\").addEventListener(\"click\", function () {\n"
    "    api(\"/api/logout\", { method: \"POST\" }).finally(function () {\n"
    "      state.loggedIn = false;\n"
    "      if (state.ws) { state.ws.onclose = null; state.ws.close(); }\n"
    "      if (state.pollTimer) clearInterval(state.pollTimer);\n"
    "      state.me = null;\n"
    "      state.peer = null;\n"
    "      $(\"app-screen\").classList.add(\"hidden\");\n"
    "      $(\"auth-screen\").classList.remove(\"hidden\");\n"
    "      $(\"login-password\").value = \"\";\n"
    "    });\n"
    "  });\n"
    "\n"
    "  function onAuthenticated(username) {\n"
    "    state.me = username;\n"
    "    state.loggedIn = true;\n"
    "    $(\"me-name\").textContent = username;\n"
    "    $(\"me-avatar\").textContent = initials(username);\n"
    "    $(\"auth-screen\").classList.add(\"hidden\");\n"
    "    $(\"app-screen\").classList.remove(\"hidden\");\n"
    "    connectWebSocket();\n"
    "    loadUsers();\n"
    "    state.pollTimer = setInterval(loadUsers, 4000);\n"
    "  }\n"
    "\n"
    "  // ---------- users / sidebar ----------\n"
    "\n"
    "  function loadUsers() {\n"
    "    api(\"/api/users\").then(function (res) {\n"
    "      if (!res.ok) return;\n"
    "      state.users = res.data.users || [];\n"
    "      renderUsers();\n"
    "    });\n"
    "  }\n"
    "\n"
    "  function renderUsers() {\n"
    "    var filter = $(\"search-input\").value.trim().toLowerCase();\n"
    "    var list = $(\"user-list\");\n"
    "    list.innerHTML = \"\";\n"
    "\n"
    "    var visible = state.users.filter(function (u) {\n"
    "      return u.username.toLowerCase().indexOf(filter) !== -1;\n"
    "    });\n"
    "\n"
    "    if (visible.length === 0) {\n"
    "      var empty = document.createElement(\"div\");\n"
    "      empty.id = \"empty-users\";\n"
    "      empty.textContent = state.users.length === 0\n"
    "        ? \"No other users yet. Ask a friend to sign up!\"\n"
    "        : \"No matches.\";\n"
    "      list.appendChild(empty);\n"
    "      return;\n"
    "    }\n"
    "\n"
    "    visible.forEach(function (u) {\n"
    "      var row = document.createElement(\"div\");\n"
    "      row.className = \"contact\" + (state.peer === u.username ? \" active\" : \"\");\n"
    "      row.innerHTML =\n"
    "        \"<div class='avatar'>\" + initials(u.username) +\n"
    "        \"<span class='presence-dot\" + (u.online ? \" online\" : \"\") + \"'></span></div>\" +\n"
    "        \"<div><div class='contact-name'></div>\" +\n"
    "        \"<div class='contact-sub'>\" + (u.online ? \"online\" : \"offline\") + \"</div></div>\";\n"
    "      row.querySelector(\".contact-name\").textContent = u.username;\n"
    "      row.addEventListener(\"click\", function () { selectPeer(u.username); });\n"
    "      list.appendChild(row);\n"
    "    });\n"
    "\n"
    "    if (state.peer) {\n"
    "      var peerData = state.users.find(function (u) { return u.username === state.peer; });\n"
    "      $(\"peer-status\").textContent = peerData && peerData.online ? \"online\" : \"offline\";\n"
    "    }\n"
    "  }\n"
    "\n"
    "  function selectPeer(username) {\n"
    "    state.peer = username;\n"
    "    renderUsers();\n"
    "\n"
    "    $(\"no-chat\").classList.add(\"hidden\");\n"
    "    $(\"chat-header\").classList.remove(\"hidden\");\n"
    "    $(\"messages\").classList.remove(\"hidden\");\n"
    "    $(\"composer\").classList.remove(\"hidden\");\n"
    "\n"
    "    $(\"peer-name\").textContent = username;\n"
    "    $(\"peer-avatar\").textContent = initials(username);\n"
    "\n"
    "    var peerData = state.users.find(function (u) { return u.username === username; });\n"
    "    $(\"peer-status\").textContent = peerData && peerData.online ? \"online\" : \"offline\";\n"
    "\n"
    "    loadConversation(username);\n"
    "  }\n"
    "\n"
    "  // ---------- conversation ----------\n"
    "\n"
    "  function loadConversation(peer) {\n"
    "    api(\"/api/messages/\" + encodeURIComponent(peer)).then(function (res) {\n"
    "      if (!res.ok) return;\n"
    "      var box = $(\"messages\");\n"
    "      box.innerHTML = \"\";\n"
    "      (res.data.messages || []).forEach(function (m) { appendMessage(m); });\n"
    "      box.scrollTop = box.scrollHeight;\n"
    "    });\n"
    "  }\n"
    "\n"
    "  function appendMessage(m) {\n"
    "    var isOwn = m.from === state.me;\n"
    "    var row = document.createElement(\"div\");\n"
    "    row.className = \"bubble-row\" + (isOwn ? \" own\" : \"\");\n"
    "    var bubble = document.createElement(\"div\");\n"
    "    bubble.className = \"bubble\";\n"
    "\n"
    "    var text = document.createElement(\"span\");\n"
    "    text.textContent = m.body;\n"
    "    bubble.appendChild(text);\n"
    "\n"
    "    var time = document.createElement(\"span\");\n"
    "    time.className = \"bubble-time\";\n"
    "    time.textContent = formatTime(m.created_at);\n"
    "    bubble.appendChild(time);\n"
    "\n"
    "    row.appendChild(bubble);\n"
    "    $(\"messages\").appendChild(row);\n"
    "  }\n"
    "\n"
    "  function belongsToOpenConversation(m) {\n"
    "    if (!state.peer) return false;\n"
    "    return (m.from === state.me && m.to === state.peer) ||\n"
    "           (m.from === state.peer && m.to === state.me);\n"
    "  }\n"
    "\n"
    "  // ---------- websocket ----------\n"
    "\n"
    "  function connectWebSocket() {\n"
    "    if (!state.loggedIn) return;\n"
    "\n"
    "    var proto = location.protocol === \"https:\" ? \"wss\" : \"ws\";\n"
    "    var ws = new WebSocket(proto + \"://\" + location.host + \"/ws\");\n"
    "    state.ws = ws;\n"
    "    state.wsReady = false;\n"
    "\n"
    "    ws.onopen = function () {\n"
    "      var sessionId = getCookie(\"session_id\");\n"
    "      ws.send(JSON.stringify({ type: \"auth\", session_id: sessionId }));\n"
    "    };\n"
    "\n"
    "    ws.onmessage = function (evt) {\n"
    "      var data;\n"
    "      try { data = JSON.parse(evt.data); } catch (e) { return; }\n"
    "\n"
    "      if (data.type === \"auth_ok\") {\n"
    "        state.wsReady = true;\n"
    "      } else if (data.type === \"auth_error\") {\n"
    "        state.wsReady = false;\n"
    "      } else if (data.type === \"message\") {\n"
    "        if (belongsToOpenConversation(data)) {\n"
    "          appendMessage(data);\n"
    "          var box = $(\"messages\");\n"
    "          box.scrollTop = box.scrollHeight;\n"
    "        }\n"
    "        loadUsers();\n"
    "      }\n"
    "    };\n"
    "\n"
    "    ws.onclose = function () {\n"
    "      state.wsReady = false;\n"
    "      if (state.loggedIn) {\n"
    "        setTimeout(connectWebSocket, 1500);\n"
    "      }\n"
    "    };\n"
    "\n"
    "    ws.onerror = function () {\n"
    "      ws.close();\n"
    "    };\n"
    "  }\n"
    "\n"
    "  function sendCurrentMessage() {\n"
    "    var input = $(\"msg-input\");\n"
    "    var text = input.value.trim();\n"
    "    if (!text || !state.peer) return;\n"
    "\n"
    "    if (!state.ws || !state.wsReady) {\n"
    "      return;\n"
    "    }\n"
    "\n"
    "    state.ws.send(JSON.stringify({ type: \"message\", to: state.peer, body: text }));\n"
    "    input.value = \"\";\n"
    "  }\n"
    "\n"
    "  $(\"send-btn\").addEventListener(\"click\", sendCurrentMessage);\n"
    "  $(\"msg-input\").addEventListener(\"keydown\", function (e) {\n"
    "    if (e.key === \"Enter\") {\n"
    "      e.preventDefault();\n"
    "      sendCurrentMessage();\n"
    "    }\n"
    "  });\n"
    "\n"
    "  $(\"search-input\").addEventListener(\"input\", renderUsers);\n"
    "\n"
    "  // ---------- bootstrap ----------\n"
    "\n"
    "  api(\"/api/me\").then(function (res) {\n"
    "    if (res.ok) {\n"
    "      onAuthenticated(res.data.username);\n"
    "    }\n"
    "  });\n"
    "})();\n"
    "</script>\n"
    "\n"
    "</body>\n"
    "</html>\n"
    "\n";
