#ifndef BB_PASSWORD_BACKEND_H
#define BB_PASSWORD_BACKEND_H

#include <stddef.h>
#include <stdint.h>

#include "blue-bird/error/error.h"

/*
 * PBKDF2-HMAC-SHA256 password hashing backend.
 *
 * This is the only file in Blue-Bird that deals with the on-disk record
 * format for password hashes; password.c only deals with the public
 * bb_password_hash()/bb_password_verify() API and the "bb$" record tag.
 *
 * Records produced here look like:
 *
 *   $pbkdf2-sha256$i=600000$<hex salt>$<hex hash>
 *
 * (password.c prepends its own "bb" tag in front of this.)
 *
 * This backend has no dependency beyond the rest of Blue-Bird: it is
 * built on the vendored SHA-256/HMAC-SHA256 primitives in
 * blue-bird/utils/hash.h and the PBKDF2 construction in
 * internal/pbkdf2.h.
 */

/*
 * Computes the number of bytes (including the terminating NUL) that
 * _bb_password_backend_hash() needs to write a full record for the
 * given salt size and iteration count.
 */
size_t _bb_password_backend_encoded_len(size_t salt_size, uint32_t iterations);

/*
 * Derives a PBKDF2-HMAC-SHA256 hash for `password` using the given salt
 * and iteration count, and writes a complete, self-describing record
 * (algorithm, iteration count, salt and hash) into `output`.
 *
 * The salt must be generated by the caller using a cryptographically
 * secure source (see internal/random.h) - this function does not
 * generate its own salt.
 *
 * Returns BB_ERR_NULL on a null argument, or BB_ERR_HASH_FAILED if
 * `output_size` is too small.
 */
bb_error_t _bb_password_backend_hash(const char *password, const unsigned char *salt, size_t salt_size, uint32_t iterations, char *output, size_t output_size);

/*
 * Re-derives the hash for `password` using the salt and iteration count
 * embedded in `encoded` (a record as produced by
 * _bb_password_backend_hash()) and compares it against the stored hash
 * in constant time.
 *
 * Returns 1 if the password matches, 0 otherwise - including for
 * malformed/corrupted/unsupported `encoded` records, which are rejected
 * rather than crashing.
 */
int _bb_password_backend_verify(const char *password, const char *encoded);

#endif
